name: Windows SonarQube Setup

on:
  push:
    branches:
      - feature/**  # Runs on any feature branch

jobs:
  sonar_scan:
    runs-on: windows-latest  # Run on Windows

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Install SonarScanner on Windows
        run: |
          Invoke-WebRequest -Uri "https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-windows.zip" -OutFile "sonar.zip"
          Expand-Archive -Path "sonar.zip" -DestinationPath "C:\sonar-scanner"
          echo "C:\sonar-scanner\sonar-scanner-5.0.1.3006-windows\bin" | Out-File -Append -Encoding ascii $env:GITHUB_PATH

      - name: Verify SonarScanner Installation
        run: sonar-scanner.bat -v

      - name: Run SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner.bat ^
            -Dsonar.projectKey=zomato-1 ^
            -Dsonar.projectName=ZomatoProject ^
            -Dsonar.host.url=http://localhost:9000 ^
            -Dsonar.token=%SONAR_TOKEN%
